In [1]:
# import Libraries

import pandas as pd
import json

In [8]:
with open ('C://Users//arsath.d//Downloads//t20_json_files//t20_json_files//t20_wc_match_results.json')as file:
    data = json.load(file)

df_match = pd.DataFrame(data[0]['matchSummary'])
df_match.head()

,team1,team2,winner,margin,ground,matchDate,scorecard
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [11]:
df_match.shape

(45, 7)

In [12]:
df_match.rename({'scorecard': 'match_id'},axis = 1, inplace = True)
df_match.head()

,team1,team2,winner,margin,ground,matchDate,match_id
0,Namibia,Sri Lanka,Namibia,55 runs,Geelong,"Oct 16, 2022",T20I # 1823
1,Netherlands,U.A.E.,Netherlands,3 wickets,Geelong,"Oct 16, 2022",T20I # 1825
2,Scotland,West Indies,Scotland,42 runs,Hobart,"Oct 17, 2022",T20I # 1826
3,Ireland,Zimbabwe,Zimbabwe,31 runs,Hobart,"Oct 17, 2022",T20I # 1828
4,Namibia,Netherlands,Netherlands,5 wickets,Geelong,"Oct 18, 2022",T20I # 1830

In [26]:
match_ids_dict = {}

for index, row in df_match.iterrows():
    key1 = row['team1'] + ' Vs ' + row['team2']
    key2 = row['team2'] + ' Vs ' + row['team1']
    match_ids_dict[key1] = row["match_id"]
    match_ids_dict[key2] = row["match_id"]

match_ids_dict

{'Namibia Vs Sri Lanka': 'T20I # 1823',
 'Sri Lanka Vs Namibia': 'T20I # 1823',
 'Netherlands Vs U.A.E.': 'T20I # 1825',
 'U.A.E. Vs Netherlands': 'T20I # 1825',
 'Scotland Vs West Indies': 'T20I # 1826',
 'West Indies Vs Scotland': 'T20I # 1826',
 'Ireland Vs Zimbabwe': 'T20I # 1828',
 'Zimbabwe Vs Ireland': 'T20I # 1828',
 'Namibia Vs Netherlands': 'T20I # 1830',
 'Netherlands Vs Namibia': 'T20I # 1830',
 'Sri Lanka Vs U.A.E.': 'T20I # 1832',
 'U.A.E. Vs Sri Lanka': 'T20I # 1832',
 'Ireland Vs Scotland': 'T20I # 1833',
 'Scotland Vs Ireland': 'T20I # 1833',
 'West Indies Vs Zimbabwe': 'T20I # 1834',
 'Zimbabwe Vs West Indies': 'T20I # 1834',
 'Netherlands Vs Sri Lanka': 'T20I # 1835',
 'Sri Lanka Vs Netherlands': 'T20I # 1835',
 'Namibia Vs U.A.E.': 'T20I # 1836',
 'U.A.E. Vs Namibia': 'T20I # 1836',
 'Ireland Vs West Indies': 'T20I # 1837',
 'West Indies Vs Ireland': 'T20I # 1837',
 'Scotland Vs Zimbabwe': 'T20I # 1838',
 'Zimbabwe Vs Scotland': 'T20I # 1838',
 'Australia Vs New Zealand': 'T20I # 1839',
 'New Zealand Vs Australia': 'T20I # 1839',
 'Afghanistan Vs England': 'T20I # 1840',
 'England Vs Afghanistan': 'T20I # 1840',
 'Ireland Vs Sri Lanka': 'T20I # 1841',
 'Sri Lanka Vs Ireland': 'T20I # 1841',
 'India Vs Pakistan': 'T20I # 1842',
 'Pakistan Vs India': 'T20I # 1842',
 'Bangladesh Vs Netherlands': 'T20I # 1843',
 'Netherlands Vs Bangladesh': 'T20I # 1843',
 'South Africa Vs Zimbabwe': 'T20I # 1844',
 'Zimbabwe Vs South Africa': 'T20I # 1844',
 'Australia Vs Sri Lanka': 'T20I # 1845',
 'Sri Lanka Vs Australia': 'T20I # 1845',
 'England Vs Ireland': 'T20I # 1846',
 'Ireland Vs England': 'T20I # 1846',
 'Afghanistan Vs New Zealand': 'T20I # 1846a',
 'New Zealand Vs Afghanistan': 'T20I # 1846a',
 'Bangladesh Vs South Africa': 'T20I # 1847',
 'South Africa Vs Bangladesh': 'T20I # 1847',
 'India Vs Netherlands': 'T20I # 1848',
 'Netherlands Vs India': 'T20I # 1848',
 'Pakistan Vs Zimbabwe': 'T20I # 1849',
 'Zimbabwe Vs Pakistan': 'T20I # 1849',
 'Afghanistan Vs Ireland': 'T20I # 1849a',
 'Ireland Vs Afghanistan': 'T20I # 1849a',
 'Australia Vs England': 'T20I # 1849b',
 'England Vs Australia': 'T20I # 1849b',
 'New Zealand Vs Sri Lanka': 'T20I # 1850',
 'Sri Lanka Vs New Zealand': 'T20I # 1850',
 'Bangladesh Vs Zimbabwe': 'T20I # 1851',
 'Zimbabwe Vs Bangladesh': 'T20I # 1851',
 'Netherlands Vs Pakistan': 'T20I # 1852',
 'Pakistan Vs Netherlands': 'T20I # 1852',
 'India Vs South Africa': 'T20I # 1853',
 'South Africa Vs India': 'T20I # 1853',
 'Australia Vs Ireland': 'T20I # 1855',
 'Ireland Vs Australia': 'T20I # 1855',
 'Afghanistan Vs Sri Lanka': 'T20I # 1856',
 'Sri Lanka Vs Afghanistan': 'T20I # 1856',
 'England Vs New Zealand': 'T20I # 1858',
 'New Zealand Vs England': 'T20I # 1858',
 'Netherlands Vs Zimbabwe': 'T20I # 1859',
 'Zimbabwe Vs Netherlands': 'T20I # 1859',
 'Bangladesh Vs India': 'T20I # 1860',
 'India Vs Bangladesh': 'T20I # 1860',
 'Pakistan Vs South Africa': 'T20I # 1861',
 'South Africa Vs Pakistan': 'T20I # 1861',
 'Ireland Vs New Zealand': 'T20I # 1862',
 'New Zealand Vs Ireland': 'T20I # 1862',
 'Australia Vs Afghanistan': 'T20I # 1864',
 'Afghanistan Vs Australia': 'T20I # 1864',
 'England Vs Sri Lanka': 'T20I # 1867',
 'Sri Lanka Vs England': 'T20I # 1867',
 'Netherlands Vs South Africa': 'T20I # 1871',
 'South Africa Vs Netherlands': 'T20I # 1871',
 'Bangladesh Vs Pakistan': 'T20I # 1872',
 'Pakistan Vs Bangladesh': 'T20I # 1872',
 'India Vs Zimbabwe': 'T20I # 1873',
 'Zimbabwe Vs India': 'T20I # 1873',
 'New Zealand Vs Pakistan': 'T20I # 1877',
 'Pakistan Vs New Zealand': 'T20I # 1877',
 'England Vs India': 'T20I # 1878',
 'India Vs England': 'T20I # 1878',
 'England Vs Pakistan': 'T20I # 1879',
 'Pakistan Vs England': 'T20I # 1879'}

In [ ]:
match_ids_dict = {}
{
   "Namibia Vs Sri Lanka": "T20I # 1823",
   "Sri Lanka Vs Namibia": "T20I # 1823",
   "Netherlands Vs U.A.E.": "T20I # 1825",
   "U.A.E. Vs Netherlands": "T20I # 1825"
    ..
}

# batting summary

In [18]:
with open('C://Users//arsath.d//Downloads//t20_json_files//t20_json_files//t20_wc_batting_summary.json')as file:
    data = json.load(file)
    all_records = []
    
    for rec in data:
        all_records.extend(rec['battingSummary'])
df_batting = pd.DataFrame(all_records)
df_batting.head(16)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c â€ Mendis b Karunaratne,20,12,1,2,166.66
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,run out (Gunathilaka/â€ Mendis),44,28,4,0,157.14
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,c â€ Mendis b Theekshana,0,1,0,0,0.00
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,,31,16,2,2,193.75
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,c Smit b Shikongo,9,10,1,0,90.00
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendisâ€,c â€ Green b Wiese,6,6,0,0,100.00
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,c Shikongo b Frylinck,12,11,1,0,109.09
11,Namibia Vs Sri Lanka,Sri Lanka,4,Danushka Gunathilaka,c â€ Green b Shikongo,0,1,0,0,0.00
12,Namibia Vs Sri Lanka,Sri Lanka,5,Bhanuka Rajapaksa,c la Cock b Scholtz,20,21,2,0,95.23
13,Namibia Vs Sri Lanka,Sri Lanka,6,Dasun Shanaka(c),c â€ Green b Frylinck,29,23,2,1,126.08
14,Namibia Vs Sri Lanka,Sri Lanka,7,Wanindu Hasaranga de Silva,c Loftie-Eaton b Scholtz,4,8,0,0,50.00
15,Namibia Vs Sri Lanka,Sri Lanka,8,Chamika Karunaratne,c Baard b Smit,5,8,0,0,62.50

In [19]:
df_batting.tail()

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
694,Pakistan Vs England,England,3,Phil Salt,c Iftikhar Ahmed b Haris Rauf,10,9,2,0,111.11
695,Pakistan Vs England,England,4,Ben Stokes,,52,49,5,1,106.12
696,Pakistan Vs England,England,5,Harry Brook,c Shaheen Shah Afridi b Shadab Khan,20,23,1,0,86.95
697,Pakistan Vs England,England,6,Moeen Ali,b Mohammad Wasim,19,13,3,0,146.15
698,Pakistan Vs England,England,7,Liam Livingstone,,1,1,0,0,100.00

In [20]:
df_batting["out/not_out"] = df_batting.dismissal.apply(lambda x: "out" if len(x) > 0 else "not_out")
df_batting.head()

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,c Pramod Madushan b Chameera,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,c Shanaka b Pramod Madushan,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,c â€ Mendis b Karunaratne,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,c DM de Silva b Pramod Madushan,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),c Gunathilaka b PWH de Silva,20,24,0,0,83.33,out

In [22]:
# drop the column
df_batting.drop(columns=["dismissal"], inplace = True)
df_batting.head(10)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,31,16,2,2,193.75,not_out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendisâ€,6,6,0,0,100.00,out

In [25]:
# remove unnecassary words
df_batting['batsmanName'] = df_batting['batsmanName'].apply(lambda x: x.replace('â€',''))
df_batting['batsmanName'] = df_batting['batsmanName'].apply(lambda x: x.replace('\xa0',''))
df_batting.head(30)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out
5,Namibia Vs Sri Lanka,Namibia,6,Jan Frylinck,44,28,4,0,157.14,out
6,Namibia Vs Sri Lanka,Namibia,7,David Wiese,0,1,0,0,0.00,out
7,Namibia Vs Sri Lanka,Namibia,8,JJ Smit,31,16,2,2,193.75,not_out
8,Namibia Vs Sri Lanka,Sri Lanka,1,Pathum Nissanka,9,10,1,0,90.00,out
9,Namibia Vs Sri Lanka,Sri Lanka,2,Kusal Mendis,6,6,0,0,100.00,out
10,Namibia Vs Sri Lanka,Sri Lanka,3,Dhananjaya de Silva,12,11,1,0,109.09,out
11,Namibia Vs Sri Lanka,Sri Lanka,4,Danushka Gunathilaka,0,1,0,0,0.00,out
12,Namibia Vs Sri Lanka,Sri Lanka,5,Bhanuka Rajapaksa,20,21,2,0,95.23,out
13,Namibia Vs Sri Lanka,Sri Lanka,6,Dasun Shanaka(c),29,23,2,1,126.08,out
14,Namibia Vs Sri Lanka,Sri Lanka,7,Wanindu Hasaranga de Silva,4,8,0,0,50.00,out
15,Namibia Vs Sri Lanka,Sri Lanka,8,Chamika Karunaratne,5,8,0,0,62.50,out
16,Namibia Vs Sri Lanka,Sri Lanka,9,Pramod Madushan,0,0,0,0,-,out
17,Namibia Vs Sri Lanka,Sri Lanka,10,Dushmantha Chameera,8,15,0,0,53.33,out
18,Namibia Vs Sri Lanka,Sri Lanka,11,Maheesh Theekshana,11,11,0,1,100.00,not_out
19,U.A.E. Vs Netherlands,U.A.E.,1,Chirag Suri,12,20,1,0,60.00,out
20,U.A.E. Vs Netherlands,U.A.E.,2,Muhammad Waseem,41,47,1,2,87.23,out
21,U.A.E. Vs Netherlands,U.A.E.,3,Kashif Daud,15,14,0,1,107.14,out
22,U.A.E. Vs Netherlands,U.A.E.,4,Vriitya Aravind,18,21,0,0,85.71,out
23,U.A.E. Vs Netherlands,U.A.E.,5,Zawar Farid,2,4,0,0,50.00,out
24,U.A.E. Vs Netherlands,U.A.E.,6,Basil Hameed,4,4,1,0,100.00,out
25,U.A.E. Vs Netherlands,U.A.E.,7,Chundangapoyil Rizwan(c),1,2,0,0,50.00,out
26,U.A.E. Vs Netherlands,U.A.E.,8,Aayan Afzal Khan,5,7,0,0,71.42,out
27,U.A.E. Vs Netherlands,U.A.E.,9,Karthik Meiyappan,0,0,0,0,-,not_out
28,U.A.E. Vs Netherlands,U.A.E.,10,Junaid Siddique,0,1,0,0,0.00,not_out
29,U.A.E. Vs Netherlands,Netherlands,1,Vikramjit Singh,10,7,2,0,142.85,out

In [27]:
match_ids_dict["Namibia Vs Sri Lanka"]

'T20I # 1823'

In [28]:
df_batting["match_id"] = df_batting["match"].map(match_ids_dict)

df_batting.head()

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out,match_id
0,Namibia Vs Sri Lanka,Namibia,1,Michael van Lingen,3,6,0,0,50.00,out,T20I # 1823
1,Namibia Vs Sri Lanka,Namibia,2,Divan la Cock,9,9,1,0,100.00,out,T20I # 1823
2,Namibia Vs Sri Lanka,Namibia,3,Jan Nicol Loftie-Eaton,20,12,1,2,166.66,out,T20I # 1823
3,Namibia Vs Sri Lanka,Namibia,4,Stephan Baard,26,24,2,0,108.33,out,T20I # 1823
4,Namibia Vs Sri Lanka,Namibia,5,Gerhard Erasmus(c),20,24,0,0,83.33,out,T20I # 1823

In [ ]:
# export csv file above table

# process Bowling Summary

with open('C://Users//arsath.d//Downloads//t20_json_files//t20_json_files//t20_wc_bowling_summary.json')as file:
    data = json.load(file)
    all_records = []
    for rec in data:
        all_records.extend(rec['bowlingSummary'])
all_records[:2]

In [30]:
df_bowling = pd.DataFrame(all_records)
print(df_bowling.shape)
df_bowling.head()

(500, 13)

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0

In [31]:
df_bowling['match_id'] = df_bowling['match'].map(match_ids_dict)
df_bowling.head()

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls,match_id
0,Namibia Vs Sri Lanka,Sri Lanka,Maheesh Theekshana,4,0,23,1,5.75,7,0,0,2,0,T20I # 1823
1,Namibia Vs Sri Lanka,Sri Lanka,Dushmantha Chameera,4,0,39,1,9.75,6,3,1,2,0,T20I # 1823
2,Namibia Vs Sri Lanka,Sri Lanka,Pramod Madushan,4,0,37,2,9.25,6,3,1,0,0,T20I # 1823
3,Namibia Vs Sri Lanka,Sri Lanka,Chamika Karunaratne,4,0,36,1,9.00,7,3,1,1,0,T20I # 1823
4,Namibia Vs Sri Lanka,Sri Lanka,Wanindu Hasaranga de Silva,4,0,27,1,6.75,8,1,1,0,0,T20I # 1823

# export csv file above table

### Process players information

In [37]:
with open('C://Users//arsath.d//Downloads//t20_json_files//t20_json_files//t20_wc_player_info.json')as f:
    data = json.load(f)

df_players = pd.DataFrame(data)
print(df_players.shape)
df_players.head(50)

(219, 6)

,name,team,battingStyle,bowlingStyle,playingRole,description
0,Michael van Lingen,Namibia,Left hand Bat,Left arm Medium,Bowling Allrounder,
1,Divan la Cock,Namibia,Right hand Bat,Legbreak,Opening Batter,
2,Jan Nicol Loftie-Eaton,Namibia,Left hand Bat,"Right arm Medium, Legbreak",Batter,
3,Stephan Baard,Namibia,Right hand Bat,Right arm Medium fast,Batter,
4,Gerhard Erasmus(c),Namibia,Right hand Bat,Right arm Offbreak,Allrounder,
5,Jan Frylinck,Namibia,Left hand Bat,Left arm Fast medium,Allrounder,
6,David Wiese,Namibia,Right hand Bat,Right arm Medium fast,Allrounder,David Wiese joined a marked outflow of South A...
7,JJ Smit,Namibia,Right hand Bat,Left arm Medium fast,Bowling Allrounder,
8,Pathum Nissanka,Sri Lanka,Right hand Bat,,Top order Batter,
9,Kusal Mendisâ€,Sri Lanka,Right hand Bat,Legbreak,Wicketkeeper Batter,"Blessed with a compact technique, an aggressiv..."
10,Dhananjaya de Silva,Sri Lanka,Right hand Bat,Right arm Offbreak,Allrounder,A technically correct top-order batsman from t...
11,Danushka Gunathilaka,Sri Lanka,Left hand Bat,Right arm Offbreak,Allrounder,"A poised, attacking left-handed opener groomed..."
12,Bhanuka Rajapaksa,Sri Lanka,Left hand Bat,Right arm Medium,Top order Batter,"An attacking left-handed batsman, Bhanuka Raja..."
13,Dasun Shanaka(c),Sri Lanka,Right hand Bat,Right arm Medium,Allrounder,"An explosive middle-order batsman, and steady ..."
14,Wanindu Hasaranga de Silva,Sri Lanka,Right hand Bat,Legbreak,Allrounder,"A bruising lower-middle order batsman, and an ..."
15,Chamika Karunaratne,Sri Lanka,Right hand Bat,Right arm Medium fast,Bowling Allrounder,
16,Pramod Madushan,Sri Lanka,Right hand Bat,Right arm Medium fast,Bowler,
17,Dushmantha Chameera,Sri Lanka,Right hand Bat,Right arm Fast,Bowler,"Tall, slim and slippery, Dushmantha Chameera a..."
18,Maheesh Theekshana,Sri Lanka,Right hand Bat,Right arm Offbreak,Bowler,
19,Gerhard Erasmus,Namibia,Right hand Bat,Right arm Offbreak,Allrounder,
20,Bernard Scholtz,Namibia,Right hand Bat,Slow Left arm Orthodox,Bowler,Bernard Scholtz's brother Nicolaas is currentl...
21,Ben Shikongo,Namibia,Right hand Bat,Right arm Medium fast,Bowler,
22,Charith Asalanka,Sri Lanka,Left hand Bat,Right arm Offbreak,Batting Allrounder,
23,David Warner,Australia,Left hand Bat,Legbreak,Opening Batter,David Warner's extraordinary batting feats in ...
24,Aaron Finch(c),Australia,Right hand Bat,Slow Left arm Orthodox,Top order Batter,"A solidly built, aggressive batter from a coun..."
25,Mitchell Marsh,Australia,Right hand Bat,Right arm Medium,Allrounder,Part of one of the most well-known family name...
26,Glenn Maxwell,Australia,Right hand Bat,Right arm Offbreak,Batting Allrounder,"One of the fastest scorers in world cricket, G..."
27,Marcus Stoinis,Australia,Right hand Bat,Right arm Medium,Batting Allrounder,"A powerful, versatile batter and medium-pace b..."
28,Josh Hazlewood,Australia,Left hand Bat,Right arm Fast medium,Bowler,A tall and accurate fast bowler who is unrelen...
29,Pat Cummins,Australia,Right hand Bat,Right arm Fast,Bowler,Earmarked as a potential star from a young age...
30,Mitchell Starc,Australia,Left hand Bat,Left arm Fast,Bowler,"First there was Johnson, then there was Starc...."
31,Ashton Agar,Australia,Left hand Bat,Slow Left arm Orthodox,Bowler,Ashton Agar initially turned almost as many he...
32,Binura Fernando,Sri Lanka,Right hand Bat,Left arm Medium fast,Bowler,Known for his ability to generate awkward boun...
33,Lahiru Kumara,Sri Lanka,Left hand Bat,Right arm Fast,Bowler,"A robust, right-arm fast bowler from Kandy, La..."
34,Dasun Shanaka,Sri Lanka,Right hand Bat,Right arm Medium,Allrounder,"An explosive middle-order batsman, and steady ..."
35,Regis Chakabvaâ€,Zimbabwe,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,"A doughty wicketkeeper-batsman, Regis Chakabva..."
36,Craig Ervine(c),Zimbabwe,Left hand Bat,Right arm Offbreak,Middle order Batter,Few people in Zimbabwe cricket circles were su...
37,Wessly Madhevere,Zimbabwe,Right hand Bat,Right arm Offbreak,Allrounder,
38,Sean Williams,Zimbabwe,Left hand Bat,Slow Left arm Orthodox,Middle order Batter,"Sean Williams is a bold, dynamic left-hand bat..."
39,Sikandar Raza,Zimbabwe,Right hand Bat,Right arm Offbreak,Batting Allrounder,Sikandar Raza's story isn't that of your every...
40,Milton Shumba,Zimbabwe,Left hand Bat,Slow Left arm Orthodox,Top order Batter,
41,Ryan Burl,Zimbabwe,Left hand Bat,Legbreak,Middle order Batter,Ryan Burl liked playing squash when he was at ...
42,Luke Jongwe,Zimbabwe,Right hand Bat,Right arm Fast medium,Bowler,
43,Paul Stirling,Ireland,Right hand Bat,Right arm Offbreak,Batting Allrounder,Paul Stirling has long been recognised as a fo...
44,Andy Balbirnie(c),Ireland,Right hand Bat,Right arm Offbreak,Batter,Already one of Ireland's star batters at No. 3...
45,Lorcan Tuckerâ€,Ireland,Right hand Bat,,Wicketkeeper Batter,
46,Harry Tector,Ireland,Right hand Bat,Right arm Offbreak,Middle order Batter,Born into a cricketing family - his brothers J...
47,Curtis Campher,Ireland,Right hand Bat,Right arm Medium fast,Allrounder,"Born in Johannesburg, raised in South Africa a..."
48,George Dockrell,Ireland,Right hand Bat,Slow Left arm Orthodox,Allrounder,George Dockrell was identified as a left-arm s...
49,Gareth Delany,Ireland,Right hand Bat,Legbreak Googly,Batting Allrounder,

In [39]:
# remove unnecessary words 
df_players['name'] = df_players['name'].apply(lambda x: x.replace('â€',''))
df_players['name'] = df_players['name'].apply(lambda x: x.replace('\xa0',''))
df_players.head(20)

,name,team,battingStyle,bowlingStyle,playingRole,description
0,Michael van Lingen,Namibia,Left hand Bat,Left arm Medium,Bowling Allrounder,
1,Divan la Cock,Namibia,Right hand Bat,Legbreak,Opening Batter,
2,Jan Nicol Loftie-Eaton,Namibia,Left hand Bat,"Right arm Medium, Legbreak",Batter,
3,Stephan Baard,Namibia,Right hand Bat,Right arm Medium fast,Batter,
4,Gerhard Erasmus(c),Namibia,Right hand Bat,Right arm Offbreak,Allrounder,
5,Jan Frylinck,Namibia,Left hand Bat,Left arm Fast medium,Allrounder,
6,David Wiese,Namibia,Right hand Bat,Right arm Medium fast,Allrounder,David Wiese joined a marked outflow of South A...
7,JJ Smit,Namibia,Right hand Bat,Left arm Medium fast,Bowling Allrounder,
8,Pathum Nissanka,Sri Lanka,Right hand Bat,,Top order Batter,
9,Kusal Mendis,Sri Lanka,Right hand Bat,Legbreak,Wicketkeeper Batter,"Blessed with a compact technique, an aggressiv..."
10,Dhananjaya de Silva,Sri Lanka,Right hand Bat,Right arm Offbreak,Allrounder,A technically correct top-order batsman from t...
11,Danushka Gunathilaka,Sri Lanka,Left hand Bat,Right arm Offbreak,Allrounder,"A poised, attacking left-handed opener groomed..."
12,Bhanuka Rajapaksa,Sri Lanka,Left hand Bat,Right arm Medium,Top order Batter,"An attacking left-handed batsman, Bhanuka Raja..."
13,Dasun Shanaka(c),Sri Lanka,Right hand Bat,Right arm Medium,Allrounder,"An explosive middle-order batsman, and steady ..."
14,Wanindu Hasaranga de Silva,Sri Lanka,Right hand Bat,Legbreak,Allrounder,"A bruising lower-middle order batsman, and an ..."
15,Chamika Karunaratne,Sri Lanka,Right hand Bat,Right arm Medium fast,Bowling Allrounder,
16,Pramod Madushan,Sri Lanka,Right hand Bat,Right arm Medium fast,Bowler,
17,Dushmantha Chameera,Sri Lanka,Right hand Bat,Right arm Fast,Bowler,"Tall, slim and slippery, Dushmantha Chameera a..."
18,Maheesh Theekshana,Sri Lanka,Right hand Bat,Right arm Offbreak,Bowler,
19,Gerhard Erasmus,Namibia,Right hand Bat,Right arm Offbreak,Allrounder,

In [40]:
df_players[df_players['team'] == 'India']

,name,team,battingStyle,bowlingStyle,playingRole,description
127,KL Rahul,India,Right hand Bat,,Opening Batter,"A tall, elegant right-hand batsman who can kee..."
128,Rohit Sharma(c),India,Right hand Bat,Right arm Offbreak,Top order Batter,"Languid and easy on the eye, Rohit Sharma owne..."
129,Virat Kohli,India,Right hand Bat,Right arm Medium,Top order Batter,India has given to the world many a great cric...
130,Suryakumar Yadav,India,Right hand Bat,"Right arm Medium, Right arm Offbreak",Batter,Hard-hitting 360-degree batter Suryakumar Yada...
131,Axar Patel,India,Left hand Bat,Slow Left arm Orthodox,Bowling Allrounder,Left-arm spinner Axar Patel has been increasin...
132,Hardik Pandya,India,Right hand Bat,Right arm Medium fast,Allrounder,Hardik Pandya swears by living life king size ...
133,Dinesh Karthik,India,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,Not many would forget the sight of Dinesh Kart...
134,Ravichandran Ashwin,India,Right hand Bat,Right arm Offbreak,Bowling Allrounder,R Ashwin took the tricks and skills he learned...
135,Bhuvneshwar Kumar,India,Right hand Bat,Right arm Medium,Bowler,"At the time of his India debut in 2012, Bhuvne..."
136,Arshdeep Singh,India,Left hand Bat,Left arm Medium fast,Bowler,
137,Mohammed Shami,India,Right hand Bat,Right arm Fast,Bowler,Mohammed Shami was India's leading fast bowler...
192,Deepak Hooda,India,Right hand Bat,Right arm Offbreak,Allrounder,"An allrounder who can bat in any position, Dee..."
211,Rishabh Pant,India,Left hand Bat,,Wicketkeeper Batter,"A match-turning, swashbuckling batter-keeper i..."

In [ ]:
# Export CSV File above table